<p>As Sprites CSS são uma forma de reduzir o número de pedidos HTTP feitos para os recursos gr&aacute;ficos, pelo seu site. As imagens são combinadas numa imagem alargada nas coordenadas X e Y definidas. Ap&oacute;s atribuir a imagem gerada aos elementos referentes da página, a propriedade CSS <code>background-position</code> pode ser utilizada para deslocar a &aacute;rea vis&iacute;vel necessária para a componente gr&aacute;fica.</p>
<p>Esta t&eacute;cnica pode ser muito eficaz para melhorar o desempenho do site, nomeadamente em situa&ccedil;&otilde;es em que muitas imagens pequenas, tais como os &iacute;cones de menu, s&atilde;o utilizadas. A <a href="http://www.yahoo.com/"> homepage do Yahoo!</a>, por exemplo, aplica esta t&eacute;cnica exactamente para isso.</p>
<h2>Gotchas</h2>
<p>Existem alguns bugs realmente irritantes que deve considerar quando criar Sprites CSS.</p>
<h3>Opera</h3>
<p>O Opera (pelo menos quanto &agrave; vers&atilde;o 9.0) n&atilde;o vai reconhecer uma posi&ccedil;&atilde;o do fundo superior a 2042px ou inferior a -2042px, usando esse valor limite em vez. A ferramenta contorna este bug, criando novas colunas dentro da imagem de sa&iacute;da sempre que o limite vertical &eacute; alcan&ccedil;ado.</p>
<h3>Safari</h3>
<p><a href="http://creativebits.org/webdev/safari_background_repeat_bug_fix">O Safari tem um problema com a repeti&ccedil;&atilde;o de imagens de fundo </a>. Felizmente, isso pode ser facilmente resolvido especificando um valor de afastamento horizontal suficientemente grande (configur&aacute;vel).</p>
<h2>Leitura</h2>
<p>A <a href="http://www.alistapart.com/">A List Apart</a> publicou um artigo intitulado <a href="http://www.alistapart.com/articles/sprites">CSS Sprites: Image Slicing's Kiss of Death</a> que explica o conceito por detr&aacute;s das Sprites CSS. Se esta t&eacute;cnica &eacute; nova para si, sugerimos que v&aacute; &agrave; <a href="http://www.alistapart.com/">A List Apart</a> e d&ecirc; uma olhadela.</p>