<p>Les Sprites CSS sont un moyen de r&#233;duire le nombre de requêtes HTTP faites sur les ressources images de votre site. Les images sont regroup&#233;es en une seule grande image, et sont accessibles via leurs coordonn&#233;es X et Y au sein de l'image. En affectant l'image g&#233;n&#233;r&#233;e aux bons &#233;l&#233;ments de la page la propri&#233;t&#233; CSS <code>background-position</code> peut alors être utilis&#233;e afin de ne rendre visible que la zone cible de l'image Sprite.</p>
<p>Cette technique est utilis&#233;e afin d'am&#233;liorer les performances d'un site, le gain de performance est significatif dans beaucoup de situations notamment dans le cas o&#249; il y a beaucoup de petites images, telles que les ic&#244;nes de menus. La <a href="http://www.yahoo.com/">page d'accueil de Yahoo!</a>, par exemple, utilise exactement cette technique.</p>
<h2>Probl&#232;mes courants</h2>
<p>Il y a quelques bogues de navigateurs vraiment tr&#232;s ennuyeux &#224; prendre en compte lors de la cr&#233;ation de Sprites CSS.</p>
<h3>Opera</h3>
<p>Opera (dans les versions inf&#233;rieures ou &#233;gales &#224; la version 9.0) ne reconnais pas une position de fond (<code>background-position</code>) sup&#233;rieure &#224; 2042px ou inf&#233;rieure &#224; -2042px et utilise ces limites &#224; la place. L'outil fait attention &#224; cela en cr&#233;ant une nouvelle colonne avec les images d'entr&#233;es &#224; chaque fois que la limite verticale est atteinte.</p>
<h3>Safari</h3>
<p><a href="http://creativebits.org/webdev/safari_background_repeat_bug_fix">Safari a un probl&#232;me avec la r&#233;p&#233;tition des images de fond</a>. Heureusement cela peut être facilement r&#233;solu en sp&#233;cifiant une valeur d'espacement vertical plus large (configurable).</p>
<h2>Lectures Compl&#233;mentaires</h2>
<p><a href="http://www.alistapart.com/">A List Apart</a> a publi&#233; un article intitul&#233; <a href="http://www.alistapart.com/articles/sprites">CSS Sprites: Image Slicing's Kiss of Death</a> qui explique les concepts cach&#233;s derri&#232;re les Sprites CSS. Si vous êtes novice avec cette technique, nous vous sugg&#233;rons fortement la rubrique <a href="http://www.alistapart.com/">A List Apart</a> et jetez un coup d'oeil.</p>