<p>Gli sprite CSS rappresentano una tecnica per ridurre il numero di richieste HTTP fatte per accedere alle immagini usate sul tuo sito. Le immagini vengono combinate in una immagine pi&ugrave; grande a definite coordinate X ed Y. Assegnando l'immagine generata ad elementi rilevanti della pagina, la propriet&agrave; CSS <code>background-position</code> pu&ograve; essere usata per spostare l'area visibile sulla sotto-immagine desiderata.</p>
<p>Questa tecnica pu&ograve; essere molto efficace per migliorare le performance del tuo sito, in maniera particolare quando vengono utilizzate molte immagini di piccole dimensioni, come nel caso di icone di un menu. L'<a href="http://www.yahoo.com/">home page di Yahoo!</a>, per esempio, usa questa tecnica esattamente a questo scopo.</p>
<h2>Gotchas</h2>
<p>Sono presenti un paio di bug in alcuni browser, da tener presenti quando si generano gli sprite CSS.</p>
<h3>Opera</h3>
<p>Opera (almeno fino alla versione 9.0) non riconosce valori per la <code>background-position</code> maggiori di 2042px o minori di -2042px, utilizzando quei valori quando si esce da tale intervallo. Questo tool genera automaticamente nuove colonne di immagini ogni volta che il limite verticale viene raggiunto.</p>
<h3>Safari</h3>
<p><a href="http://creativebits.org/webdev/safari_background_repeat_bug_fix">Safari presenta un problema nella gestione delle immagini di background ripetute</a>. Fortunatamente, questo pu&ograve; essere facilmente risolto specificando un offset orizzontale (configurabile) sufficientemente grande..</p>
<h2>Dettagli ulteriori</h2>
<p><a href="http://www.alistapart.com/">A List Apart</a> ha pubblicato un articolo intitolato <a href="http://www.alistapart.com/articles/sprites">CSS Sprites: Image Slicing's Kiss of Death</a> che spiega i concetti di base degli sprite CSS. Per chi si avvicina per la prima volta a questa tecnica, consigliamo vivamente di visitare <a href="http://www.alistapart.com/">A List Apart</a> e di dargli un'occhiata.</p>